GnssMeta:
	g++ -I include/ -I ../GnssMetadata/include/ -I ../GnssMetadata/lib/tinyxml2/ -I ../GnssMetadata/lib/GnssMetadata/Xml/ -I ../GnssMetadata/lib/GnssMetadata/ -I ../GnssMetadata/lib/GnssMetadata/Xml/ build/*.o lib/*.cpp -D LINUX -w -fmax-errors=1 -fpermissive -std=c++11 -lpthread  -o TestApp 

